apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: {{ default .Release.Namespace .Values.global.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ default "cG9zdGdyZXNfcGFzc3dvcmQ=" (get (default dict .Values.database) "password") | quote }}
